add_newline = true

# [  ](bold green)\
format = """
$directory\
$git_branch\
$git_status\
$character"""

right_format = """
$rust
$golang
$docker_context
$java
$python
$nodejs
$lua
$package
"""

palette = "fih"

[palettes.cust]
flamingo = '#f2cdcd'
maroon = '#eba0ac'
peach = '#fab387'

[palettes.fih]
bluer = '#afc9d0'
orang = '#BD6F3E'
yello = '#dbb26c'
pears = '#97ad6e'


[username]
format = " [$user]($style)"
show_always = true
style_user = "green"
style_root = "bold red"

[directory]
format = '[ $path]($style)'
style = "bold bluer"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = ""

[git_branch]
# format = '\[[$symbol$branch(:$remote_branch)]($style)\]'
# format = ' [git:\(](bold blue)[$branch]($style)[\)](bold blue)'
format = '[\(](bold blue)[$branch](bold cyan)[\)](bold blue)'
symbol = " "
style = "bold red"

[git_status]
format = "[ ><](bold blue)[$all_status>](bold blue)[$ahead_behind]($style)"
conflicted = '[*](bold red)'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = "⇡${ahead_count}⇣${behind_count}"
untracked = "[/](bold green)"
stashed = '[/](bold blue)'
modified = "[/](bold orang)"
staged = "[/](bold cyan)"
renamed = "[/](bold yello)"
typechanged = "[/](bold pears)"
deleted = '[/](bold red)'
style = 'maroon'

[cmd_duration]
disabled = false
format = '\[[$duration]($style)\]'
min_time = 1

[character]
error_symbol = " [󱏳 ](bold red)"
# error_symbol = " [✗](bold yellow)"
# success_symbol = " [  ](bold green)"
# success_symbol = " [ ](bold green)"
# success_symbol = " [󱎟 ](bold green)"
success_symbol = " [󰈺 ](bold blue)"
# success_symbol = " [❯](bold green)"


[fill]
symbol = "─"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = "󰟓 "
format = ' [${symbol}]($style)'

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = "󰎙 "
format = ' [${symbol}]($style)'

[package]
symbol = " "
format = ' [\($version\)]($style)'

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = ' [$virtualenv ${symbol}]($style)'

[ruby]
symbol = " "

[rust]
symbol = " "
format = ' [$virtualenv ${symbol}]($style)'

[swift]
symbol = "ﯣ "

[lua]
symbol = " "
format = ' [${symbol}]($style)'
